# Ubuntu 14.04 Trusty support
dist: trusty

os:
  - linux

sudo: required

language: cpp

compiler:
  - gcc
  - clang

notifications:
    email:
        on_success: never
        on_failure: always

install:
    - libopencv-dev

script:
    - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . --target all
