# Ubuntu 14.04 Trusty support
dist: trusty

os:
  - linux

language: cpp

compiler:
  - gcc
  - clang

notifications:
    email:
        on_success: never
        on_failure: always

before_install:
    - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty # for qt5.5
    - sudo apt-get -qq update
    - sudo apt-get install -qq libopencv-dev

install:
  - sudo apt-get -y install qt55[QTPACKAGE]

script:
    - source /opt/qt55/bin/qt55-env.sh
    - /opt/qt55/bin/qmake
    - make
    - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . --target all
