# Ubuntu 14.04 Trusty support
dist: trusty

os:
  - linux

language: cpp

compiler:
  - gcc
  - clang

notifications:
    email:
        on_success: never
        on_failure: always
env:
  - QT_BASE=57
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -qq libopencv-dev
    - if [ "$QT_BASE" = "57" ]; then sudo add-apt-repository ppa:beineri/opt-qt57-trusty -y; fi

install:
    - if [ "$QT_BASE" = "57" ]; then sudo apt-get install -qq qt57base; source /opt/qt57/bin/qt57-env.sh; fi

script:
    - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . --target all
