# Ubuntu 14.04 Trusty support
dist: trusty

os:
  - linux

language: cpp

compiler:
  - gcc
  - clang

notifications:
    email:
        on_success: never
        on_failure: always

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libopencv-dev

script:
    - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . --target all
