# Ubuntu 14.04 Trusty support
dist: trusty

os:
  - linux

language: cpp

compiler:
  - gcc
  - clang

cache:
  directories:
  - opencv-out

notifications:
    email:
        on_success: never
        on_failure: always

before_install:
    - sudo apt-get -qq update
    # install opencv dependencies
    - sudo apt-get -qq install libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev

before_script:
    # install opencv from git repo
    - git clone https://github.com/opencv/opencv.git
    - cd opencv
    - git checkout 2.4.13
    - cd ..
    - mkdir -p opencv-out
    - cd opencv-out
    - cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local ../opencv
    - make -j 2 # travis has 2 cores, so let's use them
    - sudo make install
    - cd ../

script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DTESTS=ON
    - make all
    - make check
