# Ubuntu 14.04 Trusty support
dist: trusty

os:
  - linux

sudo: required

language: cpp

compiler:
  - gcc
  - clang

notifications:
    email:
        on_success: never
        on_failure: always

script: echo "do make here"
